In [2]:
import numpy as np

In [21]:
np.empty((2,2),dtype="int8")

array([[1, 1],
       [1, 1]], dtype=int8)

In [22]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [23]:
np.full((3, 3), fill_value=7, dtype=int)


array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [25]:
reference_array = np.array([[1, 2], [3, 4]])
zeros_like_array = np.zeros_like(reference_array)
print("\nZeros like reference array:\n", zeros_like_array)





Zeros like reference array:
 [[0 0]
 [0 0]]


In [26]:
ones_like_array = np.ones_like(reference_array)
print("\nOnes like reference array:\n", ones_like_array)




Ones like reference array:
 [[1 1]
 [1 1]]


In [27]:
new_list = [1, 2, 3, 4]
converted_array = np.array(new_list)
print("\nConverted numpy array:\n", converted_array)



Converted numpy array:
 [1 2 3 4]


Array Manipulation: Numerical Ranges and Array indexing

In [28]:
np.arange(10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.arange(10, 50)


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [37]:
arr = np.arange(9).reshape(3,3)
print(arr)




[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [38]:
identity_matrix = np.eye(3)
print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [39]:
random_array = np.random.random(30)
print("Mean:", random_array.mean())


Mean: 0.6082401870512799


In [40]:
array_10x10 = np.random.random((10,10))
print("Minimum:", array_10x10.min())
print("Maximum:", array_10x10.max())


Minimum: 0.008615086945306993
Maximum: 0.998395456908223


In [41]:
zero_array = np.zeros(10)
zero_array[4] = 1
print(zero_array)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [42]:
arr = np.array([1,2,0,0,4,0])
reversed_arr = arr[::-1]
print(reversed_arr)


[0 4 0 0 2 1]


In [43]:
border_array = np.ones((5,5))
border_array[1:-1, 1:-1] = 0
print(border_array)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [44]:
checkerboard = np.zeros((8,8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)


[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [47]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])

v = np.array([9, 10])
w = np.array([11, 12])


In [48]:
add_result = v + w
print("Addition:", add_result)


Addition: [20 22]


In [49]:
subtract_result = v - w
print("Subtraction:", subtract_result)


Subtraction: [-2 -2]


In [51]:
multiply_result = v * 3
print("Multiplication:", multiply_result)



Multiplication: [27 30]


In [52]:
square_result = v ** 2
print("Square:", square_result)



Square: [ 81 100]


In [53]:
dot_v_w = np.dot(v, w)
dot_x_v = np.dot(x, v)
dot_x_y = np.dot(x, y)

print("Dot product (v.w):", dot_v_w)
print("Dot product (x.v):", dot_x_v)
print("Dot product (x.y):\n", dot_x_y)


Dot product (v.w): 219
Dot product (x.v): [29 77]
Dot product (x.y):
 [[19 22]
 [50 58]]


In [54]:
concat_xy_rows = np.concatenate((x, y), axis=0)
concat_vw_columns = np.column_stack((v, w))

print("Concatenate x and y along rows:\n", concat_xy_rows)
print("Concatenate v and w along column:\n", concat_vw_columns)


Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along column:
 [[ 9 11]
 [10 12]]


In [55]:
try:
    concat_x_v = np.concatenate((x, v))
    print(concat_x_v)
except ValueError as e:
    print("Error:", e)


Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


In [56]:
fixed_concat = np.concatenate((x, v.reshape(1,2)), axis=0)
print("Fixed concatenation:\n", fixed_concat)


Fixed concatenation:
 [[ 1  2]
 [ 3  5]
 [ 9 10]]


Matrix Operations

In [57]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])


In [58]:
A_inv = np.linalg.inv(A)
identity_check = np.dot(A, A_inv)

print("A inverse:\n", A_inv)
print("\nA * A⁻¹ =\n", identity_check)


A inverse:
 [[-2.    1.  ]
 [ 1.75 -0.75]]

A * A⁻¹ =
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [59]:
AB = np.dot(A, B)
BA = np.dot(B, A)

print("AB =\n", AB)
print("\nBA =\n", BA)
print("\nAre AB and BA equal?", np.array_equal(AB, BA))


AB =
 [[23 13]
 [51 29]]

BA =
 [[36 44]
 [13 16]]

Are AB and BA equal? False


In [60]:
left_side = np.transpose(AB)
right_side = np.dot(np.transpose(B), np.transpose(A))

print("(AB)ᵀ =\n", left_side)
print("\nBᵀ Aᵀ =\n", right_side)
print("\nEquality check:", np.array_equal(left_side, right_side))


(AB)ᵀ =
 [[23 51]
 [13 29]]

Bᵀ Aᵀ =
 [[23 51]
 [13 29]]

Equality check: True


Solve System of Equations Using Matrix Inverse

In [62]:
A2 = np.array([[2, -3, 1],
               [1, -1, 2],
               [3, 1, -1]])

B2 = np.array([-1, -3, 9])


In [64]:
X2 = np.linalg.solve(A2, B2)
print("Solution using solve():", X2)


Solution using solve(): [ 2.  1. -2.]


In [65]:
import time
import numpy as np
import random


In [66]:
list1 = list(range(1_000_000))
list2 = list(range(1_000_000))

start = time.time()
result_list_add = [list1[i] + list2[i] for i in range(len(list1))]
end = time.time()

print("Python List Addition Time:", end - start, "seconds")


Python List Addition Time: 0.1035773754119873 seconds


In [67]:
arr1 = np.arange(1_000_000)
arr2 = np.arange(1_000_000)

start = time.time()
result_np_add = arr1 + arr2
end = time.time()

print("NumPy Addition Time:", end - start, "seconds")


NumPy Addition Time: 0.004932403564453125 seconds


In [68]:
start = time.time()
result_list_mul = [list1[i] * list2[i] for i in range(len(list1))]
end = time.time()
print("\nPython Multiplication Time:", end - start)

start = time.time()
result_np_mul = arr1 * arr2
end = time.time()
print("NumPy Multiplication Time:", end - start)



Python Multiplication Time: 0.22378253936767578
NumPy Multiplication Time: 0.016019582748413086


In [69]:
start = time.time()
dot_list = sum(list1[i] * list2[i] for i in range(len(list1)))
end = time.time()
print("\nPython Dot Product Time:", end - start)

start = time.time()
dot_np = np.dot(arr1, arr2)
end = time.time()
print("NumPy Dot Product Time:", end - start)



Python Dot Product Time: 0.10635733604431152
NumPy Dot Product Time: 0.0018749237060546875


In [72]:
matrix1 = [[random.random() for _ in range(1000)] for _ in range(1000)]
matrix2 = [[random.random() for _ in range(1000)] for _ in range(1000)]

start = time.time()
result_matrix = [[sum(a*b for a,b in zip(row,col))
                  for col in zip(*matrix2)] for row in matrix1]
end = time.time()

print("\nPython Matrix Multiplication Time:", end - start)



Python Matrix Multiplication Time: 197.97224617004395


In [73]:
mat1 = np.random.rand(1000,1000)
mat2 = np.random.rand(1000,1000)

start = time.time()
mat_result = np.dot(mat1, mat2)
end = time.time()

print("NumPy Matrix Multiplication Time:", end - start)


NumPy Matrix Multiplication Time: 0.11982941627502441
